packages:
  - packages/*
  - packages/playground/*

allowBuilds:
  esbuild: true
  "@swc/core": true
  nx: true
  sharp: true
  vue-demi: true

catalog:
  "@biomejs/biome": ^2.5.7
  "@rolldown/plugin-babel": ^0.2.3
  "@tsdown/css": ^0.22.14
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.4
  "@ungap/structured-clone": ^1.3.3
  "@vitejs/plugin-react": ^6.0.5
  classnames: ^2.5.1
  framer-motion: ^13.0.0
  jotai-babel: ^0.3.0
  react: ^19.2.8
  react-dom: ^19.2.8
  sharp: ^0.35.3
  tsdown: ^0.22.14
  typedoc: ^0.28.20
  typedoc-plugin-markdown: ^4.12.0
  typescript: =6.0.3
  vite: ^8.2.1
  vitest: ^4.1.10

overrides:
  typescript: =6.0.3

patchedDependencies:
  "@astrojs/starlight": patches/@astrojs__starlight.patch
  monaco-editor@0.56.0: patches/monaco-editor@0.56.0.patch
